package model;
// Generated Nov 18, 2016 10:56:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblAccountJournalmapping generated by hbm2java
 */
@Entity
@Table(name="tbl_account_journalmapping"
    ,catalog="fund_manager"
)
public class TblAccountJournalmapping  implements java.io.Serializable {


     private Integer id;
     private TblFundtypes tblFundtypes;
     private TblMasteraccounts tblMasteraccounts;
     private TblMasterjournals tblMasterjournals;
     private String process;
     private String status;
     private Set<TblTransactionsdetails> tblTransactionsdetailses = new HashSet<TblTransactionsdetails>(0);
     private Set<TblInvestments> tblInvestmentses = new HashSet<TblInvestments>(0);

    public TblAccountJournalmapping() {
    }

    public TblAccountJournalmapping(TblFundtypes tblFundtypes, TblMasteraccounts tblMasteraccounts, TblMasterjournals tblMasterjournals, String process, String status, Set<TblTransactionsdetails> tblTransactionsdetailses, Set<TblInvestments> tblInvestmentses) {
       this.tblFundtypes = tblFundtypes;
       this.tblMasteraccounts = tblMasteraccounts;
       this.tblMasterjournals = tblMasterjournals;
       this.process = process;
       this.status = status;
       this.tblTransactionsdetailses = tblTransactionsdetailses;
       this.tblInvestmentses = tblInvestmentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fundId")
    public TblFundtypes getTblFundtypes() {
        return this.tblFundtypes;
    }
    
    public void setTblFundtypes(TblFundtypes tblFundtypes) {
        this.tblFundtypes = tblFundtypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accountNo")
    public TblMasteraccounts getTblMasteraccounts() {
        return this.tblMasteraccounts;
    }
    
    public void setTblMasteraccounts(TblMasteraccounts tblMasteraccounts) {
        this.tblMasteraccounts = tblMasteraccounts;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="journalId")
    public TblMasterjournals getTblMasterjournals() {
        return this.tblMasterjournals;
    }
    
    public void setTblMasterjournals(TblMasterjournals tblMasterjournals) {
        this.tblMasterjournals = tblMasterjournals;
    }

    
    @Column(name="process", length=100)
    public String getProcess() {
        return this.process;
    }
    
    public void setProcess(String process) {
        this.process = process;
    }

    
    @Column(name="status", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblAccountJournalmapping")
    public Set<TblTransactionsdetails> getTblTransactionsdetailses() {
        return this.tblTransactionsdetailses;
    }
    
    public void setTblTransactionsdetailses(Set<TblTransactionsdetails> tblTransactionsdetailses) {
        this.tblTransactionsdetailses = tblTransactionsdetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblAccountJournalmapping")
    public Set<TblInvestments> getTblInvestmentses() {
        return this.tblInvestmentses;
    }
    
    public void setTblInvestmentses(Set<TblInvestments> tblInvestmentses) {
        this.tblInvestmentses = tblInvestmentses;
    }




}


