package model;
// Generated Nov 18, 2016 10:56:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblMasterjournals generated by hbm2java
 */
@Entity
@Table(name="tbl_masterjournals"
    ,catalog="fund_manager"
)
public class TblMasterjournals  implements java.io.Serializable {


     private int journalNo;
     private TblFundtypes tblFundtypes;
     private String journalName;
     private String journalDescription;
     private String typeOfJournal;
     private String status;
     private Set<TblAccountJournalmapping> tblAccountJournalmappings = new HashSet<TblAccountJournalmapping>(0);

    public TblMasterjournals() {
    }

	
    public TblMasterjournals(int journalNo) {
        this.journalNo = journalNo;
    }
    public TblMasterjournals(int journalNo, TblFundtypes tblFundtypes, String journalName, String journalDescription, String typeOfJournal, String status, Set<TblAccountJournalmapping> tblAccountJournalmappings) {
       this.journalNo = journalNo;
       this.tblFundtypes = tblFundtypes;
       this.journalName = journalName;
       this.journalDescription = journalDescription;
       this.typeOfJournal = typeOfJournal;
       this.status = status;
       this.tblAccountJournalmappings = tblAccountJournalmappings;
    }
   
     @Id 

    
    @Column(name="journalNo", unique=true, nullable=false)
    public int getJournalNo() {
        return this.journalNo;
    }
    
    public void setJournalNo(int journalNo) {
        this.journalNo = journalNo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fundId")
    public TblFundtypes getTblFundtypes() {
        return this.tblFundtypes;
    }
    
    public void setTblFundtypes(TblFundtypes tblFundtypes) {
        this.tblFundtypes = tblFundtypes;
    }

    
    @Column(name="journalName", length=100)
    public String getJournalName() {
        return this.journalName;
    }
    
    public void setJournalName(String journalName) {
        this.journalName = journalName;
    }

    
    @Column(name="journalDescription", length=100)
    public String getJournalDescription() {
        return this.journalDescription;
    }
    
    public void setJournalDescription(String journalDescription) {
        this.journalDescription = journalDescription;
    }

    
    @Column(name="typeOfJournal", length=100)
    public String getTypeOfJournal() {
        return this.typeOfJournal;
    }
    
    public void setTypeOfJournal(String typeOfJournal) {
        this.typeOfJournal = typeOfJournal;
    }

    
    @Column(name="status", length=100)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblMasterjournals")
    public Set<TblAccountJournalmapping> getTblAccountJournalmappings() {
        return this.tblAccountJournalmappings;
    }
    
    public void setTblAccountJournalmappings(Set<TblAccountJournalmapping> tblAccountJournalmappings) {
        this.tblAccountJournalmappings = tblAccountJournalmappings;
    }




}


