package model;
// Generated Nov 18, 2016 10:56:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblTransactiontype generated by hbm2java
 */
@Entity
@Table(name="tbl_transactiontype"
    ,catalog="fund_manager"
)
public class TblTransactiontype  implements java.io.Serializable {


     private Integer transactionTypeId;
     private String transactionDescription;
     private String transTypeState;
     private Set<TblTransactionsdetails> tblTransactionsdetailses = new HashSet<TblTransactionsdetails>(0);

    public TblTransactiontype() {
    }

	
    public TblTransactiontype(String transTypeState) {
        this.transTypeState = transTypeState;
    }
    public TblTransactiontype(String transactionDescription, String transTypeState, Set<TblTransactionsdetails> tblTransactionsdetailses) {
       this.transactionDescription = transactionDescription;
       this.transTypeState = transTypeState;
       this.tblTransactionsdetailses = tblTransactionsdetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TransactionTypeId", unique=true, nullable=false)
    public Integer getTransactionTypeId() {
        return this.transactionTypeId;
    }
    
    public void setTransactionTypeId(Integer transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }

    
    @Column(name="TransactionDescription", length=100)
    public String getTransactionDescription() {
        return this.transactionDescription;
    }
    
    public void setTransactionDescription(String transactionDescription) {
        this.transactionDescription = transactionDescription;
    }

    
    @Column(name="TransTypeState", nullable=false, length=10)
    public String getTransTypeState() {
        return this.transTypeState;
    }
    
    public void setTransTypeState(String transTypeState) {
        this.transTypeState = transTypeState;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblTransactiontype")
    public Set<TblTransactionsdetails> getTblTransactionsdetailses() {
        return this.tblTransactionsdetailses;
    }
    
    public void setTblTransactionsdetailses(Set<TblTransactionsdetails> tblTransactionsdetailses) {
        this.tblTransactionsdetailses = tblTransactionsdetailses;
    }




}


